export default function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-16">
      <h1 className="text-4xl font-extrabold text-gray-900 mb-8">Privacy Policy</h1>
      
      <div className="prose prose-lg text-gray-600 space-y-8">
        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Data Collection & Usage</h2>
          <p>
            Sakinah collects personal data, preferences, and psychological insights strictly for the purpose of 
            facilitating matrimonial matchmaking via the Neuro-Intellectual System (NIS). Your data is never sold, 
            rented, or shared with third-party advertisers.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">2. KYC & Identity Protection</h2>
          <p>
            To verify identities and maintain a secure environment, we collect government-issued ID documents and live selfies. 
            These files are encrypted, processed strictly for verification, and securely archived. They are never 
            visible to other users on the platform.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Photo Privacy & Mutual Interest</h2>
          <p>
            Sakinah prioritizes character over appearance. By default, your profile photos are blurred to all candidates. 
            Your photos will only be revealed to a specific candidate if and when both of you express mutual interest in 
            each other's character-based profiles.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Matchmaking Data</h2>
          <p>
            The psychological profile generated by the NIS is internal and strictly confidential. Candidates will never 
            see your specific answers to compatibility questions, your compatibility scores, or your psychological metrics. 
            They will only see the public facts you provide in your profile setup.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Security Practices</h2>
          <p>
            We employ industry-standard encryption, secure server architecture, and stringent access controls to protect 
            your personal data. However, no internet transmission is 100% secure. You are responsible for keeping your 
            password safe and logging out on shared devices.
          </p>
        </section>
      </div>
    </div>
  );
}
