
from nis.models.user_profile import UserProfile
from nis.models.match_preference import MatchPreference
from nis.models.candidate_profile import CandidateProfile

mock_users_data = [
    {
        "user_id": "user_1",
        "name": "User 1",
        "age": 21,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 161,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_2",
        "name": "User 2",
        "age": 22,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 162,
        "marital_status": "NEVER_MARRIED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_3",
        "name": "User 3",
        "age": 23,
        "gender": "MALE",
        "location": "CityA",
        "tradition": "DEFAULT",
        "height_cm": 163,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_4",
        "name": "User 4",
        "age": 24,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 164,
        "marital_status": "DIVORCED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_5",
        "name": "User 5",
        "age": 25,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 165,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_6",
        "name": "User 6",
        "age": 26,
        "gender": "FEMALE",
        "location": "CityA",
        "tradition": "SUNNI",
        "height_cm": 166,
        "marital_status": "NEVER_MARRIED",
        "education_level": "BACHELORS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_7",
        "name": "User 7",
        "age": 27,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 167,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_8",
        "name": "User 8",
        "age": 28,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 168,
        "marital_status": "DIVORCED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_9",
        "name": "User 9",
        "age": 29,
        "gender": "MALE",
        "location": "CityA",
        "tradition": "DEFAULT",
        "height_cm": 169,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_10",
        "name": "User 10",
        "age": 30,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 170,
        "marital_status": "NEVER_MARRIED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_11",
        "name": "User 11",
        "age": 31,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 171,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_12",
        "name": "User 12",
        "age": 32,
        "gender": "FEMALE",
        "location": "CityA",
        "tradition": "SUNNI",
        "height_cm": 172,
        "marital_status": "DIVORCED",
        "education_level": "BACHELORS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_13",
        "name": "User 13",
        "age": 33,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 173,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_14",
        "name": "User 14",
        "age": 34,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 174,
        "marital_status": "NEVER_MARRIED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_15",
        "name": "User 15",
        "age": 35,
        "gender": "MALE",
        "location": "CityA",
        "tradition": "DEFAULT",
        "height_cm": 175,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_16",
        "name": "User 16",
        "age": 36,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 176,
        "marital_status": "DIVORCED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_17",
        "name": "User 17",
        "age": 37,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 177,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_18",
        "name": "User 18",
        "age": 38,
        "gender": "FEMALE",
        "location": "CityA",
        "tradition": "SUNNI",
        "height_cm": 178,
        "marital_status": "NEVER_MARRIED",
        "education_level": "BACHELORS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_19",
        "name": "User 19",
        "age": 39,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 179,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_20",
        "name": "User 20",
        "age": 40,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 180,
        "marital_status": "DIVORCED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": True,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_21",
        "name": "User 21",
        "age": 41,
        "gender": "MALE",
        "location": "CityA",
        "tradition": "DEFAULT",
        "height_cm": 181,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": False,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_22",
        "name": "User 22",
        "age": 42,
        "gender": "FEMALE",
        "location": "CityB",
        "tradition": "SUNNI",
        "height_cm": 182,
        "marital_status": "NEVER_MARRIED",
        "education_level": "BACHELORS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "BLOCKED",
        "private_notes": None,
        "_dealbreaker": ""
    },
    {
        "user_id": "user_23",
        "name": "User 23",
        "age": 43,
        "gender": "MALE",
        "location": "CityB",
        "tradition": "DEFAULT",
        "height_cm": 183,
        "marital_status": "NEVER_MARRIED",
        "education_level": "MASTERS",
        "occupation": "DOCTOR",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": "SMOKER"
    },
    {
        "user_id": "user_24",
        "name": "User 24",
        "age": 44,
        "gender": "FEMALE",
        "location": "CityA",
        "tradition": "SUNNI",
        "height_cm": 184,
        "marital_status": "DIVORCED",
        "education_level": "BACHELORS",
        "occupation": "ENGINEER",
        "work_outlook": "CAREER_FOCUSED",
        "religious_practice_level": "MODERATE",
        "islamic_environment_preference": "MODERATE",
        "is_verified": True,
        "is_banned": False,
        "has_required_data": True,
        "marriage_readiness": "READY",
        "emotional_steadiness": "HIGH",
        "anger_level": "LOW",
        "repair_style": "APOLOGETIC",
        "communication_style": "OPEN",
        "attachment_style": "SECURE",
        "family_involvement": "MEDIUM",
        "family_pressure_level": "LOW",
        "boundary_strength": "HIGH",
        "financial_responsibility": "HIGH",
        "lifestyle_pattern": "ACTIVE",
        "safety_status": "SAFE",
        "private_notes": None,
        "_dealbreaker": ""
    }
]
mock_preferences_data = [
    {
        "pref_id": "pref_1",
        "preferred_min_age": 20,
        "preferred_max_age": 30,
        "age_is_strict": True,
        "preferred_min_height_cm": None,
        "preferred_max_height_cm": None,
        "height_is_strict": False,
        "preferred_marital_statuses": [
            "NEVER_MARRIED",
            "DIVORCED"
        ],
        "marital_status_is_strict": False,
        "preferred_locations": [
            "CityA"
        ],
        "location_is_strict": True,
        "relocation_open": False,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [],
        "education_is_strict": False,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": None,
        "family_involvement_preference": None,
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": None,
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    },
    {
        "pref_id": "pref_2",
        "preferred_min_age": 20,
        "preferred_max_age": 30,
        "age_is_strict": False,
        "preferred_min_height_cm": None,
        "preferred_max_height_cm": None,
        "height_is_strict": False,
        "preferred_marital_statuses": [
            "NEVER_MARRIED",
            "DIVORCED"
        ],
        "marital_status_is_strict": False,
        "preferred_locations": [
            "CityA"
        ],
        "location_is_strict": False,
        "relocation_open": True,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [],
        "education_is_strict": False,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": None,
        "family_involvement_preference": None,
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": None,
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    },
    {
        "pref_id": "pref_3",
        "preferred_min_age": 20,
        "preferred_max_age": 30,
        "age_is_strict": False,
        "preferred_min_height_cm": 170,
        "preferred_max_height_cm": 200,
        "height_is_strict": True,
        "preferred_marital_statuses": [
            "NEVER_MARRIED"
        ],
        "marital_status_is_strict": True,
        "preferred_locations": [
            "CityA"
        ],
        "location_is_strict": False,
        "relocation_open": False,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [],
        "education_is_strict": False,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": None,
        "family_involvement_preference": None,
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": None,
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    },
    {
        "pref_id": "pref_4",
        "preferred_min_age": 20,
        "preferred_max_age": 30,
        "age_is_strict": False,
        "preferred_min_height_cm": None,
        "preferred_max_height_cm": None,
        "height_is_strict": False,
        "preferred_marital_statuses": [
            "NEVER_MARRIED",
            "DIVORCED"
        ],
        "marital_status_is_strict": False,
        "preferred_locations": [
            "CityA"
        ],
        "location_is_strict": False,
        "relocation_open": False,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [
            "MASTERS"
        ],
        "education_is_strict": True,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": None,
        "family_involvement_preference": None,
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": None,
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    },
    {
        "pref_id": "pref_5",
        "preferred_min_age": 20,
        "preferred_max_age": 30,
        "age_is_strict": False,
        "preferred_min_height_cm": None,
        "preferred_max_height_cm": None,
        "height_is_strict": False,
        "preferred_marital_statuses": [
            "NEVER_MARRIED",
            "DIVORCED"
        ],
        "marital_status_is_strict": False,
        "preferred_locations": [
            "CityA"
        ],
        "location_is_strict": False,
        "relocation_open": False,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [],
        "education_is_strict": False,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": "EARLY",
        "family_involvement_preference": "HIGH",
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": None,
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    },
    {
        "pref_id": "pref_6",
        "preferred_min_age": 20,
        "preferred_max_age": 30,
        "age_is_strict": False,
        "preferred_min_height_cm": None,
        "preferred_max_height_cm": None,
        "height_is_strict": False,
        "preferred_marital_statuses": [
            "NEVER_MARRIED",
            "DIVORCED"
        ],
        "marital_status_is_strict": False,
        "preferred_locations": [
            "CityA"
        ],
        "location_is_strict": False,
        "relocation_open": False,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [],
        "education_is_strict": False,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": None,
        "family_involvement_preference": None,
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": "OPEN",
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [
            "SMOKER"
        ],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    },
    {
        "pref_id": "pref_7",
        "preferred_min_age": 90,
        "preferred_max_age": 100,
        "age_is_strict": True,
        "preferred_min_height_cm": 250,
        "preferred_max_height_cm": 300,
        "height_is_strict": True,
        "preferred_marital_statuses": [
            "WIDOWED"
        ],
        "marital_status_is_strict": True,
        "preferred_locations": [
            "Antarctica"
        ],
        "location_is_strict": True,
        "relocation_open": False,
        "preferred_tradition": None,
        "tradition_importance": "LOW",
        "religious_practice_importance": None,
        "preferred_islamic_environment": None,
        "preferred_education_levels": [],
        "education_is_strict": False,
        "preferred_occupations": [],
        "occupation_is_strict": False,
        "preferred_work_outlook": [],
        "work_outlook_is_strict": False,
        "financial_responsibility_expectation": None,
        "wali_involvement_timing": None,
        "family_involvement_preference": None,
        "family_expectations": [],
        "family_boundaries_importance": None,
        "wali_visibility_preference": None,
        "preferred_lifestyle_pattern": None,
        "preferred_daily_routine": None,
        "preferred_living_arrangement": None,
        "household_responsibility_preference": None,
        "financial_lifestyle_preference": None,
        "communication_preference": None,
        "conflict_style_preference": None,
        "difficult_conflict_styles": [],
        "important_character_traits": [],
        "preferred_repair_style": None,
        "dealbreakers": [],
        "non_negotiables": [],
        "flexible_preferences": [],
        "custom_dealbreakers": [],
        "photo_visibility_comfort": None,
        "in_app_communication_comfort": None,
        "reportable_behaviors": [],
        "confirmed_honest_preferences": True,
        "confirmed_no_match_over_wrong_match": True,
        "confirmed_private_preferences_not_public": True,
        "confirmed_raya_does_not_decide": True
    }
]

mock_users = []
for data in mock_users_data:
    db_trait = data.pop("_dealbreaker")
    profile = UserProfile(**data)
    # Store dealbreaker trait separately if we want, or just mock it in CandidateProfile later
    # We will attach it as a hidden attribute to use when constructing CandidateProfile
    setattr(profile, "_dealbreaker", db_trait)
    mock_users.append(profile)

mock_match_preferences = {}
for data in mock_preferences_data:
    pid = data.pop("pref_id")
    mock_match_preferences[pid] = MatchPreference(**data)

def get_mock_user(user_id: str):
    for u in mock_users:
        if u.user_id == user_id:
            return u
    return None

def get_match_preference(preference_id: str):
    return mock_match_preferences.get(preference_id)

def get_candidate_pool_for_seeker(seeker_id: str):
    candidates = []
    for u in mock_users:
        if u.user_id != seeker_id:
            db_traits = [getattr(u, "_dealbreaker")] if getattr(u, "_dealbreaker") else []
            candidates.append(CandidateProfile(
                candidate_id=u.user_id,
                profile=u,
                known_dealbreaker_traits=db_traits
            ))
    return candidates
